-- CINEGENOME LAB / Supabase PostgreSQL schema
-- Run in the Supabase SQL editor.
-- DNA values are project-owned computed/editorial scores (0-100), not TMDB fields.

create table if not exists public.movies (
  id bigint generated by default as identity primary key,
  tmdb_id bigint unique,
  title text not null,
  original_title text,
  release_year int check (release_year between 1888 and 2200),
  director text,
  country text,
  overview text,
  poster_path text,
  backdrop_path text,
  genres text[] not null default '{}',
  tags text[] not null default '{}',
  metadata_source text not null default 'curated',
  source_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.movie_dna (
  movie_id bigint primary key references public.movies(id) on delete cascade,
  surrealism smallint not null check (surrealism between 0 and 100),
  loneliness smallint not null check (loneliness between 0 and 100),
  chaos smallint not null check (chaos between 0 and 100),
  romance smallint not null check (romance between 0 and 100),
  nostalgia smallint not null check (nostalgia between 0 and 100),
  intensity smallint not null check (intensity between 0 and 100),
  pacing smallint not null check (pacing between 0 and 100),
  visual_extremity smallint not null check (visual_extremity between 0 and 100),
  narrative_complexity smallint not null check (narrative_complexity between 0 and 100),
  darkness smallint not null check (darkness between 0 and 100),
  humor smallint not null check (humor between 0 and 100),
  dream_logic smallint not null check (dream_logic between 0 and 100),
  model_version text not null default 'starter-1.0.0',
  scoring_method text not null default 'editorial',
  scored_at timestamptz not null default now()
);

create index if not exists movies_title_idx on public.movies using btree (lower(title));
create index if not exists movies_year_idx on public.movies (release_year);
create index if not exists movies_genres_gin on public.movies using gin (genres);
create index if not exists movies_tags_gin on public.movies using gin (tags);

create or replace view public.movie_genomes as
select
  m.id, m.tmdb_id, m.title, m.original_title, m.release_year, m.director,
  m.country, m.overview, m.poster_path, m.backdrop_path, m.genres, m.tags,
  d.surrealism, d.loneliness, d.chaos, d.romance, d.nostalgia,
  d.intensity, d.pacing, d.visual_extremity, d.narrative_complexity,
  d.darkness, d.humor, d.dream_logic, d.model_version, d.scoring_method
from public.movies m
join public.movie_dna d on d.movie_id = m.id;

-- Browser clients may read the public catalog. Writes remain server-side only.
alter table public.movies enable row level security;
alter table public.movie_dna enable row level security;

drop policy if exists "public read movies" on public.movies;
create policy "public read movies" on public.movies for select to anon, authenticated using (true);

drop policy if exists "public read movie dna" on public.movie_dna;
create policy "public read movie dna" on public.movie_dna for select to anon, authenticated using (true);

grant select on public.movies to anon, authenticated;
grant select on public.movie_dna to anon, authenticated;
grant select on public.movie_genomes to anon, authenticated;

-- Optional profile table for future authenticated users.
create table if not exists public.user_experiments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  experiment_type text not null check (experiment_type in ('favorite','crossbreed','mutation')),
  title text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.user_experiments enable row level security;
create policy "users read own experiments" on public.user_experiments for select to authenticated using (auth.uid() = user_id);
create policy "users insert own experiments" on public.user_experiments for insert to authenticated with check (auth.uid() = user_id);
create policy "users delete own experiments" on public.user_experiments for delete to authenticated using (auth.uid() = user_id);
grant select, insert, delete on public.user_experiments to authenticated;
